[package]

name = "static_file"
version = "0.1.0"
authors = ["Zach Pomerantz <zmp@umich.edu>"]

[lib]

name = "static_file"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.mount]

git = "https://github.com/iron/mount.git"

[dependencies.iron-test]

git = "https://github.com/reem/iron-test"

[dev-dependencies.router]

git = "https://github.com/iron/router.git"
